# Enrichissement des données foncières avec la population communale

In [17]:
import pandas as pd

data = pd.read_csv("../clean_data/ValeursFoncieres_nettoyees.csv",
                   dtype={
                       "Code commune": str,
                        "No plan": str,
                        "Code type local": str,
                        "Code departement": str
                        })

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_8836\2211764025.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../clean_data/ValeursFoncieres_nettoyees.csv",

In [18]:
data['CodeINSEE'] = data['Code departement'] + data['Code commune']

In [19]:
pop = pd.read_csv("../data/donnees_communes.csv", sep=";", encoding="utf-8")

In [20]:
pop['CodeINSEE'] = pop['COM'].astype(str).str.zfill(5)

data = data.merge(pop[['CodeINSEE', 'PTOT']], on='CodeINSEE', how='left')

data.rename(columns={'PTOT': 'Population'}, inplace=True)

data.head()

,Date mutation,Nature mutation,Valeur fonciere,Code postal,Commune,Code departement,Code commune,Section,No plan,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,prix_m2,CodeINSEE,Population
0,2024-01-03,Vente,329500.0,01170,GEX,01,173,AI,551,2,Appartement,89.0,4.0,NaN,3702.0,01173,13742.0
1,2024-01-03,Vente,94500.0,01150,LAGNIEU,01,202,AC,198,2,Appartement,74.0,3.0,65.0,1277.0,01202,7442.0
2,2024-01-03,Vente,94500.0,01150,LAGNIEU,01,202,AC,198,2,Appartement,32.0,2.0,65.0,2953.0,01202,7442.0
3,2024-01-03,Vente,220000.0,01640,BOYEUX-SAINT-JEROME,01,056,C,2523,1,Maison,40.0,1.0,488.0,5500.0,01056,370.0
4,2024-01-03,Vente,220000.0,01640,BOYEUX-SAINT-JEROME,01,056,C,2524,1,Maison,80.0,2.0,858.0,2750.0,01056,370.0

In [21]:
densite =  pd.read_excel("../data/densite_commune.xlsx")

In [22]:
data = pd.merge(data, densite[['codgeo', 'dens_pop']], left_on='CodeINSEE', right_on='codgeo', how='left')
data.drop(columns=['codgeo'], inplace=True)
data.head(5)

,Date mutation,Nature mutation,Valeur fonciere,Code postal,Commune,Code departement,Code commune,Section,No plan,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,prix_m2,CodeINSEE,Population,dens_pop
0,2024-01-03,Vente,329500.0,01170,GEX,01,173,AI,551,2,Appartement,89.0,4.0,NaN,3702.0,01173,13742.0,408.69
1,2024-01-03,Vente,94500.0,01150,LAGNIEU,01,202,AC,198,2,Appartement,74.0,3.0,65.0,1277.0,01202,7442.0,267.21
2,2024-01-03,Vente,94500.0,01150,LAGNIEU,01,202,AC,198,2,Appartement,32.0,2.0,65.0,2953.0,01202,7442.0,267.21
3,2024-01-03,Vente,220000.0,01640,BOYEUX-SAINT-JEROME,01,056,C,2523,1,Maison,40.0,1.0,488.0,5500.0,01056,370.0,21.07
4,2024-01-03,Vente,220000.0,01640,BOYEUX-SAINT-JEROME,01,056,C,2524,1,Maison,80.0,2.0,858.0,2750.0,01056,370.0,21.07

In [23]:
nom_departement = pd.read_excel("../data/nom_departement.xlsx")
data = pd.merge(data, nom_departement, left_on='Code departement', right_on='DEP', how='left')
data.drop(columns='DEP', inplace=True)
data.head(5)

,Date mutation,Nature mutation,Valeur fonciere,Code postal,Commune,Code departement,Code commune,Section,No plan,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain,prix_m2,CodeINSEE,Population,dens_pop,LIB_DEP
0,2024-01-03,Vente,329500.0,01170,GEX,01,173,AI,551,2,Appartement,89.0,4.0,NaN,3702.0,01173,13742.0,408.69,Ain
1,2024-01-03,Vente,94500.0,01150,LAGNIEU,01,202,AC,198,2,Appartement,74.0,3.0,65.0,1277.0,01202,7442.0,267.21,Ain
2,2024-01-03,Vente,94500.0,01150,LAGNIEU,01,202,AC,198,2,Appartement,32.0,2.0,65.0,2953.0,01202,7442.0,267.21,Ain
3,2024-01-03,Vente,220000.0,01640,BOYEUX-SAINT-JEROME,01,056,C,2523,1,Maison,40.0,1.0,488.0,5500.0,01056,370.0,21.07,Ain
4,2024-01-03,Vente,220000.0,01640,BOYEUX-SAINT-JEROME,01,056,C,2524,1,Maison,80.0,2.0,858.0,2750.0,01056,370.0,21.07,Ain

In [25]:
data.to_csv("../clean_data/ValeursFoncieres_enrichies.csv", index=False, encoding="utf-8")